### ISSUE TITLE
Yardım lazım

### ISSUE THREAD

**Issue by xffury** [lazymule/LogoObjectsSample#1]
Logo object ile kestiğim perakende satış faturasının , fatura listesinde görünen toplamlar yanlış geliyor.

**Comment by lazymule** [comment]
Merhaba muhtemelen birim fiyatları kdv dahil yazmıyorsunuz 

`  Fatura.New;
  Fatura.DataFields.FieldByName('TYPE').Value := 7; ---perakende satış faturası
  Fatura.DataFields.FieldByName('NUMBER').Value := '~';
  Fatura.DataFields.FieldByName('DOC_NUMBER').Value := 'A00001';
  Fatura.DataFields.FieldByName('AUXIL_CODE').Value := 'AUTO';
  Fatura.DataFields.FieldByName('DATE').Value := '22.02.2020';
  Fatura.DataFields.FieldByName('DOC_DATE').Value := '22.02.2020';
  LogoBaglantisi.PackTime(12, 12, 12, Saat);
  Fatura.DataFields.FieldByName('TIME').Value := Saat;
  Fatura.DataFields.FieldByName('ARP_CODE').Value := 'CR-001';
  FaturaSatirlari := Fatura.DataFields.FieldByName('TRANSACTIONS').Lines;
  FaturaSatirlari.AppendLine;
  FaturaSatirlari[0].FieldByName('TYPE').Value := 0;
  FaturaSatirlari[0].FieldByName('MASTER_CODE').Value := 'STK-001';
  FaturaSatirlari[0].FieldByName('QUANTITY').Value := 1;
  FaturaSatirlari[0].FieldByName('PRICE').Value := 100;------------ kdv dahil fiyat
  FaturaSatirlari[0].FieldByName('UNIT_CODE').Value := 'ADET';
  FaturaSatirlari[0].FieldByName('VAT_RATE').Value := 18;`

bir örnek paylaşırsan yardımcı olmaya çalışırım.
