### ISSUE TITLE
Harici sistem üzerinden kullanım

### ISSUE THREAD

**Issue by ertankucukoglu** [lazymule/LogoObjectsSample#2]
Merhaba,

Merkez-Şube arasında sadece VPN ile erişim imkanı var ise bu durumda Şube üzerindeki uygulama merkeze logo objects kullanarak erişim sağlayabilir mi?

Teşekkürler.

**Comment by lazymule** [comment]
merhaba denemedim ama hız büyük faktör malum logonun dosyaları büyük şöyle birşey denene bilir lisans sunucusunu isimden değil ip olarak ayarlayın uzaktaki makineye merkedeki logo klasörü kopyalayın vpn bağlayın ve register bat dosyasını yönetici olarak çalıştırın ve sysden terminal kaydı yapın bence sorunsuz çalışacaktır.

yerel ağda sorunsuz kullanıyoruz vpn de de sıkıntı çıkarma bence

**Comment by ertankucukoglu** [comment]
Evet. Bu şekilde erişim sağlandı. Beklediğimden daha yavaş ancak çözüm Windows Servis uygulaması olarak çalışacağı için çok sorun olacağını düşünmüyorum.

Teşekkürler.
