### ISSUE TITLE
Veri okuma örneği

### ISSUE THREAD

**Issue by ertankucukoglu** [lazymule/LogoObjectsSample#3]
Merhaba,

Logo içindeki bazı sabit tanım bilgilerini okumak istiyorum.

Yaptığım denemelerin hepsi başarısız oldu. IData.Read ve IQuery ile denedim.

IData.Read okumaya uygun değil hatası verdi.
IQuery ise daha yolun başında NewQuery atamasından sonra halen "nil" olarak kalıyor ve sonrasındaki ilk işlem direk "access violation" oluyor.

Logo Objects sürümü 027500

Çok basit, tüm stok listesi veya tüm cari kart listesi okuma örneği eklemeniz mümkün mü? Sadece kod ve başlık bilgisi olsa yeterli olacaktir.

Proje dahi olması gerekmez. Bağlantı kodların da gerek yok. Mevcut örnekte bunlar var.

En azından çalıştığını bildiğim bir kod ile de denemek istedim.

Teşekkürler.

**Comment by lazymule** [comment]
Sana yardımcı olmak isterdim ama Objects  lisanslı logo imkanım yok önceki işyerimde tiger vardı aktif kullanıyordum. imkanım olsa yardımcı olmak isterdim. 
logodan neden sql zorluyorsun bence araya gereksiz bir katman giriyor tabi bu benim görüşüm GetDBConnInfo bir fonksiyon var bence buradan sql bilgilerini al bak keyfine 

örnek c# koduna baktım pek cansıkıcı birşey yok.gibi gördüm 
https://docs.logo.com.tr/public/wua/logo-objects/logo-objects-kuetuephanesi/unityapplication/newquery

sana aşağıya çevirmeye çalıştım dene başarılı olursan küçük bir örneğe çevir buraya koyalım başkalarıda faydalansın 

mail adresim kemalbayat@gmail.com bana mail atarsın

var
  LOSorgu: Query;
  TabloAdi: string;
  sql: string;
  dofoo: Boolean;
  sonuc: string;
begin

  if LogoBaglantisi.Connected then
  begin
    LOSorgu := LogoBaglantisi.NewQuery;

    TabloAdi := LogoBaglantisi.GetTableName(1, LogoBaglantisi.CurrentFirm,
      LogoBaglantisi.ActivePeriod);
    sql := 'SELECT TOP 5 LOGICALREF, CODE FROM ' + TabloAdi + ' WHERE CARDTYPE <> 22 ';

    LOSorgu.Statement := sql;

    if LOSorgu.OpenDirect then

    begin

      dofoo := LOSorgu.First;
      while dofoo do
      begin

        sonuc := sonuc +  VarToStr( LOSorgu.QueryFields[0].Value )  + '--' +
         VarToStr( LOSorgu.QueryFields[1].Value) ;

          dofoo := LOSorgu.Next;
      end;


    end ;
    Memo1.Lines.Text :=  sonuc;
